druid.driverClassName=com.mysql.cj.jdbc.Driver
druid.url=jdbc:mysql://localhost:3306/less?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
druid.username=root
druid.password=159951
initialSize=5
maxActive=10
minIdle=3
maxWait=5000